/* backend/schema/User.js */
import mongoose from "mongoose"

const userSchema = new mongoose.Schema(
  {
    // ... (Keep existing fields: email, username, password, userid, description, profilePic, pfp_status, etc.) ...
    email: { type: String, required: true, unique: true },
    username: { type: String, required: true },
    password: { type: String, required: true },
    userid: { type: String, unique: true },
    description: { type: mongoose.Schema.Types.Mixed, default: {} }, 
    profilePic: { type: String, default: "" }, 
    pfp_status: { 
      matrix: { type: Array, default: [] }, 
      background: { colors: { type: [String], default: ['#ffffff'] }, angle: { type: Number, default: 90 } }
    },
    pfp_inventory: {
      custom: [{
        id: String, // Unique timestamp ID
        matrix: Array, // Compressed pixel data
        background: { colors: [String], angle: Number },
        base64: String // Cached image for fast UI rendering
      }],
      earned: [{
        publishId: { type: mongoose.Schema.Types.ObjectId, ref: 'Publish' }, // The Route to the DB
        giftName: String, // Name of the unlocked node
        base64: String // Cached image generated by Console
      }]
    },
    // Track what is currently equipped
    active_pfp_type: { type: String, enum: ['custom', 'earned'], default: 'custom' },
    active_earned_ref: {
      publishId: { type: mongoose.Schema.Types.ObjectId, ref: 'Publish' },
      giftName: String
    },
    
    // ✅ NEW: Social Graph Arrays
    // We store ObjectIds to easily populate lists later
    followers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    following: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],

    // ... (Keep demographics)
    dob: String,
    age: Number,
    country: String,
    state: String,
    city: String,
    verified: { type: String, enum: ['normal', 'chosen', 'verified', 'paid'], default: 'normal' },
    
    // ... (Keep stats - we will sync these numbers with the array lengths)
    followersCount: { type: Number, default: 0 },
    followingCount: { type: Number, default: 0 },
    rating: { type: Number, default: 0.0 },
    weavesCount: { type: Number, default: 0 }
  },
  { timestamps: true }
)

export default mongoose.model("User", userSchema)